version: "3"

services:
  frameworkphp:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: joaovitor98/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginxcontainer:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: joaovitor98/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80
networks:
  laranet:
    driver: bridge